version: '3.3'

services:
  db-node-1:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-1:/var/lib/mysql

  db-node-2:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3361:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-2:/var/lib/mysql

  db-node-3:
    build:
      context: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: archdb
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch-network
    ports:
      - 3362:3306
    healthcheck:
      test: "/usr/bin/mysqladmin ping -h localhost --user=stud --password=stud"
      timeout: 20s
      retries: 5
    volumes:
      - maria-db-volume-3:/var/lib/mysql

  all-db:
    build:
      context: proxysql
    healthcheck:
      test: "/usr/bin/mysql -h 127.0.0.1 -P 6033 --user=stud --password=stud --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    networks:
      - arch-network
    ports:
      # Mysql Client Port
      - 6033:6033
      # Mysql Admin Port
      - 6032:6032
    depends_on:
      - db-node-1
      - db-node-2
      - db-node-3
    volumes:
      - proxysql-data:/var/lib/proxysql

  init-db:
    build:
      context: mariadb/data_generator
    networks:
      - arch-network
    depends_on:
      all-db:
        condition: service_healthy

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - arch-network
    volumes:
      - cache:/data

  auth-service:
    build:
      context: .
    environment:
      - DB_HOST=all-db
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - CACHE=cache:6379
    ports:
      - 8080:8080
    entrypoint: /app/build/auth_service
    networks:
      - arch-network
    depends_on:
      cache:
        condition: service_started
      all-db:
        condition: service_healthy

  product-service:
    build:
      context: .
    environment:
      - DB_HOST=all-db
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - CACHE=cache:6379
      - SERVICE_HOST=auth-service
    ports:
      - 8081:8081
    entrypoint: /app/build/product_service
    networks:
      - arch-network
    depends_on:
      all-db:
        condition: service_healthy

  cart-service:
    build:
      context: .
    environment:
      - DB_HOST=all-db
      - DB_PORT=6033
      - DB_DATABASE=archdb
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - CACHE=cache:6379
      - SERVICE_HOST=auth-service
      - PRODUCT_HOST=product-service
    ports:
      - 8082:8082
    entrypoint: /app/build/cart_service
    networks:
      - arch-network
    depends_on:
      all-db:
        condition: service_healthy

volumes:
  maria-db-volume-1:
  maria-db-volume-2:
  maria-db-volume-3:
  proxysql-data:
  cache:

networks:
  arch-network:
    driver: "bridge"
    external: false
